name = "nrtapi"
main = "worker.js"
compatibility_date = "2024-03-20"

# Zorg dat je 'worker.js' in dezelfde map staat als dit bestand.
# Als je typescript of een src map gebruikt, verander main naar "src/index.js"

[observability]
enabled = true
